site_name: My Docs
site_url: https://example.com/
theme:
  name: material
  language: zh

copyright: Copyright &copy; 2021 - 2021 Xie Zhong Liang

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/weibo
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/zhihu
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
    - icon: fontawesome/brands/weixin
      link: https://twitter.com/squidfunk
      name: squidfunk on Twitter
  analytics:
    provider: google
    property: G-4XFLNXT68X

  alternate:
    # Switch to 中文
    - name: 中文
      link: <your-site>/zh/
      lang: zh

    # Switch to English
    - name: English
      link: <your-site>/en/
      lang: en

    # Switch to Japanese
    - name: 日本語
      link: <your-site>/ja/
      lang: ja
